config/routes.rb
Rails.application.routes.draw do
  get 'locations/get_location'
  get 'locations/find_address'
  resources :events
  get 'event', to: 'event#index'
  get 'pages/index'
  get 'products/index'
  get 'products/show'
  get 'users/index'
  get 'users/show'
  root 'users#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
    }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def get_location
    response = { address: Geocoder.address(
    [params[:latitude], params[:longitude]]
    ) }
    render json: response.to_json
  end

  def find_address
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/find_address.html.erb
<script> 
 if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(getAddress);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
        function getAddress(position) {
            var latitude = position.coords.latitude;
            var longitude = position.coords.longitude;
        $.ajax({
            url: '<%= locations_find_address_path %>',
            type: 'GET',
            dataType: 'json',
            data: {latitude: latitude, longitude: longitude}
        });
    };
</script>

app/views/locations/get_location.html.erb
<div id="mapa">
    .done(function(data) {
        x.text(data.address)
    })
</div>


   